packages:
  - "apps/**"
  - "!apps/backend/.medusa/**"
overrides:
  "@types/react": "19.0.5"
  "@types/react-dom": "19.0.5"
  caniuse-lite: "^1.0.30001806"
allowBuilds:
  '@medusajs/telemetry': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
