"""Curated genre lookup for The Vinyl Cut catalog.

MusicBrainz's own tag data is user-submitted and inconsistent, so genre is
assigned from this small curated list instead (see vinyl_cut_prd.html,
Data Sourcing). Keyed by the seed file's artist string (the curation-time
label used to build seed.json), not MusicBrainz's own artist-credit, so a
pressing-specific MB naming quirk (e.g. "The Velvet Underground & Nico" vs.
"The Velvet Underground") never breaks the lookup.

GENRE_BY_MBID takes precedence for the rare case where an artist's catalog
legitimately spans genres per-release; it's empty today but left in place
for that override, per the pipeline doc's "keyed by MBID or artist".
"""

GENRES = [
    "Rock",
    "Pop",
    "Hip-Hop",
    "R&B/Soul",
    "Country",
    "Folk",
    "Jazz",
    "Blues",
    "Electronic",
    "Punk",
    "Metal",
    "Reggae",
    "Latin",
    "World",
]

DEFAULT_GENRE = "Rock"

GENRE_BY_MBID: dict[str, str] = {}

GENRE_BY_ARTIST: dict[str, str] = {
    "2Pac": "Hip-Hop",
    "50 Cent": "Hip-Hop",
    "A Tribe Called Quest": "Hip-Hop",
    "ABBA": "Pop",
    "AC/DC": "Rock",
    "Aaliyah": "R&B/Soul",
    "Adele": "Pop",
    "Aerosmith": "Rock",
    "Al Green": "R&B/Soul",
    "Alanis Morissette": "Rock",
    "Alice Coltrane": "Jazz",
    "Alicia Keys": "R&B/Soul",
    "Amy Winehouse": "R&B/Soul",
    "Anita Baker": "R&B/Soul",
    "Arcade Fire": "Rock",
    "Arctic Monkeys": "Rock",
    "Aretha Franklin": "R&B/Soul",
    "B.B. King": "Blues",
    "Bad Bunny": "Latin",
    "Beastie Boys": "Hip-Hop",
    "Beck": "Rock",
    "Belle and Sebastian": "Rock",
    "Beyoncé": "R&B/Soul",
    "Big Brother and the Holding Company": "Rock",
    "Big Star": "Rock",
    "Bill Withers": "R&B/Soul",
    "Billie Eilish": "Pop",
    "Billie Holiday": "Jazz",
    "Billy Joel": "Pop",
    "Björk": "Electronic",
    "Black Flag": "Punk",
    "Black Sabbath": "Metal",
    "Black Uhuru": "Reggae",
    "Blondie": "Rock",
    "Blur": "Rock",
    "Bo Diddley": "Blues",
    "Bob Dylan": "Folk",
    "Bob Dylan and the Band": "Folk",
    "Bob Marley and the Wailers": "Reggae",
    "Bon Iver": "Folk",
    "Bonnie Raitt": "Blues",
    "Boogie Down Productions": "Hip-Hop",
    "Boyz II Men": "R&B/Soul",
    "Brian Eno": "Electronic",
    "Brian Wilson": "Rock",
    "Britney Spears": "Pop",
    "Bruce Springsteen": "Rock",
    "Buddy Holly": "Rock",
    "Buzzcocks": "Punk",
    "Can": "Rock",
    "Carole King": "Folk",
    "Cat Stevens": "Folk",
    "Charles Mingus": "Jazz",
    "Chic": "R&B/Soul",
    "Chuck Berry": "Rock",
    "Cocteau Twins": "Rock",
    "Coldplay": "Rock",
    "Creedence Clearwater Revival": "Rock",
    "Crosby, Stills & Nash": "Folk",
    "Crosby, Stills, Nash & Young": "Folk",
    "Curtis Mayfield": "R&B/Soul",
    "Cyndi Lauper": "Pop",
    "D'Angelo": "R&B/Soul",
    "D'Angelo and the Vanguard": "R&B/Soul",
    "DJ Shadow": "Hip-Hop",
    "Daddy Yankee": "Latin",
    "Daft Punk": "Electronic",
    "David Bowie": "Rock",
    "De La Soul": "Hip-Hop",
    "Depeche Mode": "Electronic",
    "Derek and the Dominos": "Rock",
    "Destiny's Child": "R&B/Soul",
    "Devo": "Rock",
    "Diana Ross": "R&B/Soul",
    "Dire Straits": "Rock",
    "Dixie Chicks": "Country",
    "Dolly Parton": "Country",
    "Donna Summer": "R&B/Soul",
    "Dr. Dre": "Hip-Hop",
    "Dr. John": "R&B/Soul",
    "Drake": "Hip-Hop",
    "Dusty Springfield": "R&B/Soul",
    "Eagles": "Rock",
    "Earth, Wind & Fire": "R&B/Soul",
    "Elliott Smith": "Folk",
    "Elton John": "Pop",
    "Elvis Costello": "Rock",
    "Elvis Presley": "Rock",
    "Eminem": "Hip-Hop",
    "Eric B. & Rakim": "Hip-Hop",
    "Eric Church": "Country",
    "Erykah Badu": "R&B/Soul",
    "Etta James": "Blues",
    "Fela Kuti and Africa '70": "World",
    "Fiona Apple": "Pop",
    "Fleetwood Mac": "Rock",
    "Four Tops": "R&B/Soul",
    "Frank Ocean": "R&B/Soul",
    "Frank Sinatra": "Jazz",
    "Fugees": "Hip-Hop",
    "Funkadelic": "R&B/Soul",
    "GZA": "Hip-Hop",
    "Gang of Four": "Punk",
    "George Harrison": "Rock",
    "George Michael": "Pop",
    "Ghostface Killah": "Hip-Hop",
    "Gillian Welch": "Folk",
    "Gorillaz": "Electronic",
    "Grateful Dead": "Rock",
    "Green Day": "Punk",
    "Guns N' Roses": "Rock",
    "Hank Williams": "Country",
    "Harry Nilsson": "Pop",
    "Harry Styles": "Pop",
    "Herbie Hancock": "Jazz",
    "Hole": "Rock",
    "Howlin' Wolf": "Blues",
    "Hüsker Dü": "Punk",
    "Ice Cube": "Hip-Hop",
    "Ike & Tina Turner": "R&B/Soul",
    "Isaac Hayes": "R&B/Soul",
    "J Dilla": "Hip-Hop",
    "James Brown": "R&B/Soul",
    "James Taylor": "Folk",
    "Janet Jackson": "R&B/Soul",
    "Janis Joplin": "Rock",
    "Jason Isbell": "Country",
    "Jay-Z": "Hip-Hop",
    "Jeff Buckley": "Rock",
    "Jefferson Airplane": "Rock",
    "Jerry Lee Lewis": "Rock",
    "John Coltrane": "Jazz",
    "John Lennon": "Rock",
    "John Mayer": "Rock",
    "John Prine": "Folk",
    "Johnny Cash": "Country",
    "Joni Mitchell": "Folk",
    "Joy Division": "Punk",
    "Juvenile": "Hip-Hop",
    "Kacey Musgraves": "Country",
    "Kanye West": "Hip-Hop",
    "Kate Bush": "Pop",
    "Kelis": "R&B/Soul",
    "Kendrick Lamar": "Hip-Hop",
    "Kid Cudi": "Hip-Hop",
    "King Sunny Adé": "World",
    "Kiss": "Rock",
    "Kraftwerk": "Electronic",
    "LCD Soundsystem": "Electronic",
    "LL Cool J": "Hip-Hop",
    "Lady Gaga": "Pop",
    "Lana Del Rey": "Pop",
    "Laura Nyro": "Folk",
    "Lauryn Hill": "Hip-Hop",
    "Led Zeppelin": "Rock",
    "Leonard Cohen": "Folk",
    "Lil Wayne": "Hip-Hop",
    "Linda Ronstadt": "Rock",
    "Little Richard": "Rock",
    "Liz Phair": "Rock",
    "Lorde": "Pop",
    "Loretta Lynn": "Country",
    "Los Lobos": "Rock",
    "Lou Reed": "Rock",
    "Love": "Rock",
    "Lucinda Williams": "Country",
    "Luther Vandross": "R&B/Soul",
    "Lynyrd Skynyrd": "Rock",
    "M.I.A.": "Hip-Hop",
    "MC5": "Punk",
    "Madonna": "Pop",
    "Madvillain": "Hip-Hop",
    "Manu Chao": "World",
    "Mariah Carey": "Pop",
    "Marvin Gaye": "R&B/Soul",
    "Mary J. Blige": "R&B/Soul",
    "Massive Attack": "Electronic",
    "Maxwell": "R&B/Soul",
    "Merle Haggard": "Country",
    "Metallica": "Metal",
    "Michael Jackson": "Pop",
    "Miles Davis": "Jazz",
    "Minutemen": "Punk",
    "Miranda Lambert": "Country",
    "Missy Elliott": "Hip-Hop",
    "Mobb Deep": "Hip-Hop",
    "Motörhead": "Metal",
    "Muddy Waters": "Blues",
    "My Bloody Valentine": "Rock",
    "My Chemical Romance": "Rock",
    "N.W.A": "Hip-Hop",
    "Nas": "Hip-Hop",
    "Neil Young": "Rock",
    "Neil Young and Crazy Horse": "Rock",
    "Neutral Milk Hotel": "Folk",
    "New Order": "Electronic",
    "New York Dolls": "Punk",
    "Nick Drake": "Folk",
    "Nina Simone": "Jazz",
    "Nine Inch Nails": "Metal",
    "Nirvana": "Rock",
    "Oasis": "Rock",
    "Olivia Rodrigo": "Pop",
    "Ornette Coleman": "Jazz",
    "Otis Redding": "R&B/Soul",
    "Outkast": "Hip-Hop",
    "PJ Harvey": "Rock",
    "Parliament": "R&B/Soul",
    "Patsy Cline": "Country",
    "Patti Smith": "Punk",
    "Paul McCartney and Linda McCartney": "Rock",
    "Paul Simon": "Folk",
    "Pavement": "Rock",
    "Pearl Jam": "Rock",
    "Pet Shop Boys": "Electronic",
    "Peter Gabriel": "Rock",
    "Pink Floyd": "Rock",
    "Pixies": "Rock",
    "Portishead": "Electronic",
    "Prince": "R&B/Soul",
    "Prince and the Revolution": "R&B/Soul",
    "Public Enemy": "Hip-Hop",
    "Pulp": "Rock",
    "Queen": "Rock",
    "R.E.M.": "Rock",
    "Radiohead": "Rock",
    "Raekwon": "Hip-Hop",
    "Rage Against the Machine": "Rock",
    "Ramones": "Punk",
    "Randy Newman": "Pop",
    "Ray Charles": "R&B/Soul",
    "Red Hot Chili Peppers": "Rock",
    "Richard Thompson and Linda Thompson": "Folk",
    "Rihanna": "Pop",
    "Robert Johnson": "Blues",
    "Roberta Flack": "R&B/Soul",
    "Robyn": "Pop",
    "Rod Stewart": "Rock",
    "Rosalía": "Latin",
    "Roxy Music": "Rock",
    "Rufus featuring Chaka Khan": "R&B/Soul",
    "Run-DMC": "Hip-Hop",
    "Rush": "Rock",
    "SZA": "R&B/Soul",
    "Sade": "R&B/Soul",
    "Sam Cooke": "R&B/Soul",
    "Santana": "Rock",
    "Selena": "Latin",
    "Sex Pistols": "Punk",
    "Shakira": "Latin",
    "Shania Twain": "Country",
    "Sheryl Crow": "Rock",
    "Simon & Garfunkel": "Folk",
    "Sinéad O'Connor": "Pop",
    "Sleater-Kinney": "Punk",
    "Sly and the Family Stone": "R&B/Soul",
    "Smokey Robinson": "R&B/Soul",
    "Snoop Doggy Dogg": "Hip-Hop",
    "Solange Knowles": "R&B/Soul",
    "Sonic Youth": "Rock",
    "Sparks": "Rock",
    "Steely Dan": "Rock",
    "Stevie Wonder": "R&B/Soul",
    "Suicide": "Punk",
    "T. Rex": "Rock",
    "TLC": "R&B/Soul",
    "Talking Heads": "Rock",
    "Tame Impala": "Rock",
    "Taylor Swift": "Pop",
    "Television": "Punk",
    "The Allman Brothers Band": "Rock",
    "The B-52's": "Rock",
    "The Band": "Rock",
    "The Beach Boys": "Rock",
    "The Beatles": "Rock",
    "The Breeders": "Rock",
    "The Byrds": "Rock",
    "The Cars": "Rock",
    "The Clash": "Punk",
    "The Cure": "Rock",
    "The Doors": "Rock",
    "The Flying Burrito Brothers": "Country",
    "The Go-Go's": "Rock",
    "The Isley Brothers": "R&B/Soul",
    "The Jimi Hendrix Experience": "Rock",
    "The Kinks": "Rock",
    "The Magnetic Fields": "Pop",
    "The Meters": "R&B/Soul",
    "The Modern Lovers": "Rock",
    "The Notorious B.I.G.": "Hip-Hop",
    "The Pharcyde": "Hip-Hop",
    "The Police": "Rock",
    "The Pretenders": "Rock",
    "The Raincoats": "Punk",
    "The Replacements": "Rock",
    "The Rolling Stones": "Rock",
    "The Ronettes": "Pop",
    "The Roots": "Hip-Hop",
    "The Slits": "Punk",
    "The Smashing Pumpkins": "Rock",
    "The Smiths": "Rock",
    "The Stone Roses": "Rock",
    "The Stooges": "Punk",
    "The Strokes": "Rock",
    "The Supremes": "R&B/Soul",
    "The Temptations": "R&B/Soul",
    "The Velvet Underground": "Rock",
    "The Weeknd": "R&B/Soul",
    "The White Stripes": "Rock",
    "The Who": "Rock",
    "The Zombies": "Rock",
    "Todd Rundgren": "Rock",
    "Tom Petty": "Rock",
    "Tom Petty and the Heartbreakers": "Rock",
    "Tom Waits": "Rock",
    "Toots and the Maytals": "Reggae",
    "Tori Amos": "Pop",
    "Tracy Chapman": "Folk",
    "U2": "Rock",
    "Usher": "R&B/Soul",
    "Vampire Weekend": "Rock",
    "Van Halen": "Rock",
    "Van Morrison": "Rock",
    "Various artists": "Pop",
    "Weezer": "Rock",
    "Whitney Houston": "Pop",
    "Wilco": "Rock",
    "Willie Nelson": "Country",
    "Wire": "Punk",
    "Wu-Tang Clan": "Hip-Hop",
    "X": "Punk",
    "X-Ray Spex": "Punk",
    "Yeah Yeah Yeahs": "Rock",
    "Yes": "Rock",
    "Yo La Tengo": "Rock",
}


def genre_for(artist: str, mbid: str | None = None) -> tuple[str, bool]:
    """Returns (genre, was_curated). was_curated is False when the default
    fallback was used, so callers can log unmapped artists for review."""
    if mbid and mbid in GENRE_BY_MBID:
        return GENRE_BY_MBID[mbid], True
    if artist in GENRE_BY_ARTIST:
        return GENRE_BY_ARTIST[artist], True
    return DEFAULT_GENRE, False
